### ISSUE TITLE
Enable only for specific filetype

### ISSUE THREAD

**Issue by Shatur** [Pocco81/auto-save.nvim#14]
Hi! Currently the plugin can only exclude filetypes, but it would be nice to be able to enable the plugin only for specific filetypes.

I can do it manually using built-in ftpugin, so I don't know, maybe it worth to remove `filename_is_not` and `filetype_is_not` at all let Neovim do the job.

**Comment by Pocco81** [comment]
Hmmm I mean, wouldn't that make the plug-in less user-friendly?

Of course nvim has a built-in way of doing this, but what about adding both tables (`filetype_is(_not)`)?

This would imply that If the `is` table is not empty then the `is_not` table will be ignored regardless of its contents.

**Comment by Shatur** [comment]
> Of course nvim has a built-in way of doing this, but what about adding both tables (filetype_is(_not))?

This is also a good solution. I would like to see something like this.

But personally, I would like neovim-way a little more. We could explain how to use it in the readme :)

**Comment by magichan** [comment]
I need the introduce how to enable the plugin for the specific filetypes, Thx

**Comment by adamalbrecht** [comment]
FWIW, I stumbled upon this plugin because I was googling for a way to autosave markdown files in a specific directory. Doesn't seem like this will work, correct?

**Comment by kry00la** [comment]
> Of course nvim has a built-in way of doing this
can you share how are you doing this with nvim? (I'm beginner with nvim)

**Comment by coder3101** [comment]
I use a before save hook and abort save if the filetype is not rust effectively achieving the "save only specific file types"
```lua
autosave.hook_before_saving = function ()
    if vim.bo.filetype ~= "rust" then
        vim.g.auto_save_abort = true -- abort saving non rust files/ only save rust files
    end
end
```

**Comment by Pocco81** [comment]
Heya! please check #33 :tada:
