### ISSUE TITLE
`conditions` with hooks setup

### ISSUE THREAD

**Issue by ceigh** [Pocco81/auto-save.nvim#20]
Hello, i try to run presave hook to clear trailing spaces like this:

```lua
autosave.hook_before_saving = function()
  vim.cmd('%s/\\s\\+$//e')
end
```

But when i open NerdTree i see this error:
```
Error detected while processing TextChanged Autocommands for "*":
E5108: Error executing lua [string ":lua"]:17: Vim(substitute):E21: Cannot make changes, 'modifiable' is off
```
It looks like the save hook is done bypassing the rules.

This is with defaults. I also tried to register the config manually with:

```lua
autosave.setup({
  enabled = true,
  conditions = {
    exists = true,
    filetype_is_not = {'nerdtree'},
    modifiable = true,
  },
})
```

But it doesn't seem to be working as i suspect. How is this kind of action supposed to be performed?
Is it supposed to manually check inside `hook_before_saving` that the file is writable?

I also tried using `hook_after_saving`, but it's the same.

For now the only option is to use
```lua
events = { 'InsertLeave' }
```

Or simple 
```vim
au BufWritePre * %s/\s\+$//e
```

Using neovim `v0.6.0-dev+560-g1fdbd29df`

PS Thank you for your work! ;)

**Comment by Pocco81** [comment]
Heya! please check #33 :tada:
