### ISSUE TITLE
`execution_message` is not updated

### ISSUE THREAD

**Issue by ceigh** [Pocco81/auto-save.nvim#21]
Using the default option: 

```lua
execution_message = "AutoSave: saved at " .. vim.fn.strftime("%H:%M:%S")
```

execution message is not updated between different saves

```
AutoSave: saved at 21:36:13
```
After several other saves, the message is the same, the time does not change

Nothing serious, just a report :)

**Comment by gsa9** [comment]
Same thing here.
Meanwhile, the plugin's hook_after_saving, is working fine, and can serve for now:

autosave.hook_after_saving = function ()
	print("saved at " .. vim.fn.strftime("%H:%M:%S"))
end

**Comment by theVerusDev** [comment]
Having the same issue. Manually sourcing my config file, however, does update the message. What I figure is going on is that `execution_message` is only stored once, so it won't be updated as the actual value of `execution_message`, in this case

`execution_message = "AutoSave: saved at " .. vim.fn.strftime("%H:%M:%S")`

will only be called upon once whenever the config is sourced (either manually or at startup.)

> Same thing here. Meanwhile, the plugin's hook_after_saving, is working fine, and adding this code to my own init.lua file can serve for now:
> 
> ```
> autosave.hook_after_saving = function ()
> 	print("saved at " .. vim.fn.strftime("%H:%M:%S"))
> end
> ```

This would make sense as the hook isn't being stored, so it will always return with the correct timestamp whenever it's being called upon. Using this as a temporary workaround until OP's PR is reviewed.

**Comment by Pocco81** [comment]
#22 resolves this.

**Comment by theVerusDev** [comment]
Heads up, the init.lua and init.vim sections of the documentation have yet to reflect the new changes regarding the most recent commit.

**Comment by Pocco81** [comment]
Heya! please check #33 :tada:
