### ISSUE TITLE
Cannot be installed with Plugged

### ISSUE THREAD

**Issue by rgasper** [Pocco81/auto-save.nvim#23]
Migration of trunk branch from master to main broke Plugged installation:

in `init.vim`:
```
 Plug 'Pocco81/AutoSave.nvim'
```

```
:PlugUpdate
Updated. Elapsed time: 1.461561 sec.
[======x]

- Finishing ... Done!
x AutoSave.nvim:
    fatal: invalid reference: master
```

**Comment by Pocco81** [comment]
Which NeoVim version are you using?

**Comment by adi-g15** [comment]
> Which NeoVim version are you using?

This happens with me also:

neovim version: v0.6.1
neovim-plug: 0.10.0-3

A simple workaround is specifying the branch,

```vim
Plug 'Pocco81/AutoSave.nvim', {'branch': 'main'}
```

Thanks for the plugin though : )

**Comment by SadPersonn** [comment]
still not working with Plugged

**Comment by samtipton** [comment]
Installation completes successfully for me in vim-plug after running `:PlugInstall`, but afterwards in a new nvim editor, auto saving doesn't happen.

**Comment by Pocco81** [comment]
Heya! please check #33 :tada:
