### ISSUE TITLE
Reset debounce delay and cancel save if there is another action shortly after

### ISSUE THREAD

**Issue by primeapple** [Pocco81/auto-save.nvim#27]
First of, thanks for the plugin.

So my workflow goes the following:
1. Think a lot about the text, move around.
2. Find the place to edit
3. Delete, Insert, Change, ... all behind each other for multiple times (e.g. change word, delete next one, append some text, change next line, ...)

Currently it seems the plugin will save after every single change + debounce delay. This, at least for me, breaks other tasks that watch the files for changes (webpacker for example).

Is there any way to introduce some sort option, that resets the debounce delay, if there is a following change fast enough?

Example:
```
EDIT -100ms- EDIT -100ms- EDIT
```
would result in 3 saves, even with debounce delay at 135ms.
With the cancel of the debounce delay this would only save once.

**Comment by Pocco81** [comment]
Heya! please check #33 :tada:
