### ISSUE TITLE
`TextChanged ` event bug?

### ISSUE THREAD

**Issue by AGou-ops** [Pocco81/auto-save.nvim#31]
![2022-07-15 16-23-33 2022-07-15 16_25_52](https://user-images.githubusercontent.com/57939102/179184351-de9f0707-d168-48f5-a4c2-027833fee513.gif)

The cursor will automatically move to the beginning of the line when using the `TextChanged` option.

**Comment by Pocco81** [comment]
Heya! please check #33 :tada:
