### ISSUE TITLE
auto-save.nvim rewrite: everything changed

### ISSUE THREAD

**Issue by Pocco81** [Pocco81/auto-save.nvim#33]
Heya! I decided to rewrite auto-save because I kind of disliked the previous state of the code-base.

### Notes:

1. Backwards compatibility with previous auto-save confs won't be provided
2. This plugin is completely different from the original, so please update your settings!
3. Previous issues won't be attended because `2`. If your issue still exists please open a new one.
4. I added previous feature requests as I saw fit.

Enjoy :partying_face: :tada:

**Comment by jdhao** [comment]
It is not necessary to change the repo name if you want a rewrite...

**Comment by Pocco81** [comment]
@jdhao True, but didn't just change it because of the rewrite. I previous naming convention it followed was simply a whim of mine. The current one, however, follows what [most other neovim plugins](https://github.com/rockerBOO/awesome-neovim) use.

So it's better now :)
