### ISSUE TITLE
On Off Commands

### ISSUE THREAD

**Issue by primeapple** [Pocco81/auto-save.nvim#35]
Hi, please re-add the on/off commands, previously it was `on_off_commands = true` inside of the config table.

**Comment by Pocco81** [comment]
Hmm are you sure this is _necessary_? I already exposed the API so that users can make their commands/use it for whatever they want.

**Comment by primeapple** [comment]
What do you mean with the exposed API? You mean the callbacks and the hooks?

**Comment by Pocco81** [comment]
> What do you mean with the exposed API? 

The functions to toggle auto-save on and off

**Comment by primeapple** [comment]
I see.
Just for future reference: This one will enable: `require("auto-save").on()`, this one will disable the plugin: `require("auto-save").off()`
