### ISSUE TITLE
Keeps going to command line after saving

### ISSUE THREAD

**Issue by BrownCarter** [Pocco81/auto-save.nvim#38]
When it autosaves or I press ESC focus would go to the command line and I have to press enter to confirm and go back.

**Comment by BrownCarter** [comment]
![Uploading Screenshot_20220803-122359_Termux.png…]()

**Comment by BrownCarter** [comment]
![auto](https://user-images.githubusercontent.com/25666658/182597105-eee7e7e5-e036-4ce8-9cc4-41dfbdefba69.png)

**Comment by Pocco81** [comment]
@BrownCarter I was not able to reproduce the issue. Could you:

1. share your auto-save conf
2. confirm which branch you are on
3. write a step-by-step on how to reproduce the issue

Thanks :)
