### ISSUE TITLE
Config breaking changes not mentioned config changes in README disclaimer

### ISSUE THREAD

**Issue by stelcodes** [Pocco81/auto-save.nvim#43]
Hi there, thanks for this plugin! I got a little tripped up with the breaking changes upon updating my plugins. I like the README disclaimer, but I think it would also be helpful to add that there's breaking changes to the config and maybe link to #5. I fixed the repo renaming issues and I was confused why I was still getting more errors afterward.

**Comment by Pocco81** [comment]
Thanks for the heads-up! :)
